name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'
        coverage:
          - none
    steps:
      - uses: shivammathur/setup-php@2.26.0
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/checkout@v3
      - run: composer install --no-progress --no-ansi --no-interaction --dev --prefer-dist
      - run: composer test
